// 组件测试用的 DesktopSettings 夹具。字段集合与 Rust 侧 DesktopSettings 对齐，
// 默认刻意不含 kernel_agent —— 「未设置 = 关闭」是这个开关的语义，测试要能锁住它。
import type { DesktopSettings } from "@/lib/ipc";

export function makeSettings(overrides: Partial<DesktopSettings> = {}): DesktopSettings {
  return {
    schema_version: 3,
    language: "zh-CN",
    close_action: "tray",
    sound_enabled: false,
    theme: "dark",
    font_scale: "medium",
    font_family: "sans",
    custom_font_family: null,
    session_display: "standard",
    terminal_shell: null,
    active_workspace: null,
    recent_workspaces: [],
    default_provider_id: null,
    providers: [],
    feature_toggles: {},
    legacy_migration_complete: true,
    github_user: null,
    reasoning_effort: "medium",
    edit_mode: "review",
    budget_usd: null,
    session_budget_usd: null,
    show_system_events: false,
    web_search_engine: "duckduckgo",
    headroom_enabled: false,
    headroom_port: 8787,
    context_compression: true,
    context_window_tokens: 128000,
    price_per_million_tokens: 2,
    price_per_million_output_tokens: null,
    usage_stats: {
      total_tokens: 0,
      total_cost_usd: 0,
      today_tokens: 0,
      today_cost_usd: 0,
      week_tokens: 0,
      week_cost_usd: 0,
      last_updated: null,
      by_model: [],
      recent_sessions: [],
      tool_calls_ok: 0,
      tool_calls_fail: 0,
      compaction_count: 0,
      compaction_failures: 0,
    },
    subagents: [],
    shortcuts: {},
    onboarding_completed: true,
    prompt_templates: [],
    workflows: [],
    network: {
      proxy_mode: "off",
      proxy_url: null,
      request_timeout_secs: 120,
      retry_enabled: true,
      retry_max: 2,
    },
    ...overrides,
  };
}

export const SESSION_FIXTURE = {
  id: "s-1",
  title: "重构登录页",
  created_at: "2026-09-01T00:00:00Z",
  updated_at: "2026-09-02T00:00:00Z",
  message_count: 2,
  model: "grok-4",
  pinned: false,
};
